export const CREATE_RECORDDFSSSDSS = "CREATE_RECORDDFSSSDSS";
export const CREATE_RECORDDFSSSDSS_SUCCESS = "CREATE_RECORDDFSSSDSS_SUCCESS";
export const CREATE_RECORDDFSSSDSS_FAILURE = "CREATE_RECORDDFSSSDSSLOGIN_FAILURE";

export const GET_RECORDDFSSSDSS = "GET_RECORDDFSSSDSS";
export const GET_RECORDDFSSSDSS_SUCCESS = "GET_RECORDDFSSSDSS_SUCCESS";
export const GET_RECORDDFSSSDSS_FAILURE = "GET_RECORDDFSSSDSS_FAILURE";

export const UPDATE_RECORDDFSSSDSS = "UPDATE_RECORDDFSSSDSS";
export const UPDATE_RECORDDFSSSDSS_SUCCESS = "UPDATE_RECORDDFSSSDSS_SUCCESS";
export const UPDATE_RECORDDFSSSDSS_FAILURE = "UPDATE_RECORDDFSSSDSS_FAILURE";


export const DELETE_RECORDDFSSSDSS = "DELETE_RECORDDFSSSDSS";
export const DELETE_RECORDDFSSSDSS_SUCCESS = "DELETE_RECORDDFSSSDSS_SUCCESS";
export const DELETE_RECORDDFSSSDSS_FAILURE = "DELETE_RECORDDFSSSDSS_FAILURE";