export const CREATE_RECORDSSSDSS = "CREATE_RECORDSSSDSS";
export const CREATE_RECORDSSSDSS_SUCCESS = "CREATE_RECORDSSSDSS_SUCCESS";
export const CREATE_RECORDSSSDSS_FAILURE = "CREATE_RECORDSSSDSSLOGIN_FAILURE";

export const GET_RECORDSSSDSS = "GET_RECORDSSSDSS";
export const GET_RECORDSSSDSS_SUCCESS = "GET_RECORDSSSDSS_SUCCESS";
export const GET_RECORDSSSDSS_FAILURE = "GET_RECORDSSSDSS_FAILURE";

export const UPDATE_RECORDSSSDSS = "UPDATE_RECORDSSSDSS";
export const UPDATE_RECORDSSSDSS_SUCCESS = "UPDATE_RECORDSSSDSS_SUCCESS";
export const UPDATE_RECORDSSSDSS_FAILURE = "UPDATE_RECORDSSSDSS_FAILURE";


export const DELETE_RECORDSSSDSS = "DELETE_RECORDSSSDSS";
export const DELETE_RECORDSSSDSS_SUCCESS = "DELETE_RECORDSSSDSS_SUCCESS";
export const DELETE_RECORDSSSDSS_FAILURE = "DELETE_RECORDSSSDSS_FAILURE";