version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - mysql-db
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: firstdb
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: techteam
            MYSQL_PASSWORD: 123456Aa@
            MYSQL_ROOT_HOST: localhost
volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.238.0/24
      driver: default
