version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
      - mysql-db
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
      #- node_modules:/usr/src/node-app/node_modules
    networks:
      - node-network

  frontend:
    build:
      context: ../../frontend/saldirismc/FrontEnd
      dockerfile: dockerfile
    image: saldiriweb
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:8081/v2
    ports:
      - '3000:3000'
    

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_USER: techteam
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: 127.0.0.1
      MYSQL_DATABASE: techteam
    volumes:
      - ./data:/var/lib/mysqld
      - ./data:/docker-entrypoint-initdb.d/
      - ./DatabaseScripts/get_AttendanceSumByID.sql:/docker-entrypoint-initdb.d/get_AttendanceSumByID.sql
      - ./DatabaseScripts/get_AttendanceByHours.sql:/docker-entrypoint-initdb.d/get_AttendanceByHours.sql
    ports:
      - 3306:3306
    expose:
      - 3306

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.1/24
