export const CREATE_FARARIES = "CREATE_FARARIES";
export const CREATE_FARARIES_SUCCESS = "CREATE_FARARIES_SUCCESS";
export const CREATE_FARARIES_FAILURE = "CREATE_FARARIESLOGIN_FAILURE";

export const GET_FARARIES = "GET_FARARIES";
export const GET_FARARIES_SUCCESS = "GET_FARARIES_SUCCESS";
export const GET_FARARIES_FAILURE = "GET_FARARIES_FAILURE";

export const UPDATE_FARARIES = "UPDATE_FARARIES";
export const UPDATE_FARARIES_SUCCESS = "UPDATE_FARARIES_SUCCESS";
export const UPDATE_FARARIES_FAILURE = "UPDATE_FARARIES_FAILURE";


export const DELETE_FARARIES = "DELETE_FARARIES";
export const DELETE_FARARIES_SUCCESS = "DELETE_FARARIES_SUCCESS";
export const DELETE_FARARIES_FAILURE = "DELETE_FARARIES_FAILURE";