export const CREATE_FARARI = "CREATE_FARARI";
export const CREATE_FARARI_SUCCESS = "CREATE_FARARI_SUCCESS";
export const CREATE_FARARI_FAILURE = "CREATE_FARARILOGIN_FAILURE";

export const GET_FARARI = "GET_FARARI";
export const GET_FARARI_SUCCESS = "GET_FARARI_SUCCESS";
export const GET_FARARI_FAILURE = "GET_FARARI_FAILURE";

export const UPDATE_FARARI = "UPDATE_FARARI";
export const UPDATE_FARARI_SUCCESS = "UPDATE_FARARI_SUCCESS";
export const UPDATE_FARARI_FAILURE = "UPDATE_FARARI_FAILURE";


export const DELETE_FARARI = "DELETE_FARARI";
export const DELETE_FARARI_SUCCESS = "DELETE_FARARI_SUCCESS";
export const DELETE_FARARI_FAILURE = "DELETE_FARARI_FAILURE";