export const CREATE_EMAIL_TEMPLATE = "CREATE_EMAIL_TEMPLATE";
export const CREATE_EMAIL_TEMPLATE_SUCCESS = "CREATE_EMAIL_TEMPLATE_SUCCESS";
export const CREATE_EMAIL_TEMPLATE_FAILURE = "CREATE_EMAIL_TEMPLATELOGIN_FAILURE";
