export const CREATE_RECORDSS = "CREATE_RECORDSS";
export const CREATE_RECORDSS_SUCCESS = "CREATE_RECORDSS_SUCCESS";
export const CREATE_RECORDSS_FAILURE = "CREATE_RECORDSSLOGIN_FAILURE";

export const GET_RECORDSS = "GET_RECORDSS";
export const GET_RECORDSS_SUCCESS = "GET_RECORDSS_SUCCESS";
export const GET_RECORDSS_FAILURE = "GET_RECORDSS_FAILURE";

export const UPDATE_RECORDSS = "UPDATE_RECORDSS";
export const UPDATE_RECORDSS_SUCCESS = "UPDATE_RECORDSS_SUCCESS";
export const UPDATE_RECORDSS_FAILURE = "UPDATE_RECORDSS_FAILURE";


export const DELETE_RECORDSS = "DELETE_RECORDSS";
export const DELETE_RECORDSS_SUCCESS = "DELETE_RECORDSS_SUCCESS";
export const DELETE_RECORDSS_FAILURE = "DELETE_RECORDSS_FAILURE";