export const CREATE_RECORDDFDSDSSSSDSS = "CREATE_RECORDDFDSDSSSSDSS";
export const CREATE_RECORDDFDSDSSSSDSS_SUCCESS = "CREATE_RECORDDFDSDSSSSDSS_SUCCESS";
export const CREATE_RECORDDFDSDSSSSDSS_FAILURE = "CREATE_RECORDDFDSDSSSSDSSLOGIN_FAILURE";

export const GET_RECORDDFDSDSSSSDSS = "GET_RECORDDFDSDSSSSDSS";
export const GET_RECORDDFDSDSSSSDSS_SUCCESS = "GET_RECORDDFDSDSSSSDSS_SUCCESS";
export const GET_RECORDDFDSDSSSSDSS_FAILURE = "GET_RECORDDFDSDSSSSDSS_FAILURE";

export const UPDATE_RECORDDFDSDSSSSDSS = "UPDATE_RECORDDFDSDSSSSDSS";
export const UPDATE_RECORDDFDSDSSSSDSS_SUCCESS = "UPDATE_RECORDDFDSDSSSSDSS_SUCCESS";
export const UPDATE_RECORDDFDSDSSSSDSS_FAILURE = "UPDATE_RECORDDFDSDSSSSDSS_FAILURE";


export const DELETE_RECORDDFDSDSSSSDSS = "DELETE_RECORDDFDSDSSSSDSS";
export const DELETE_RECORDDFDSDSSSSDSS_SUCCESS = "DELETE_RECORDDFDSDSSSSDSS_SUCCESS";
export const DELETE_RECORDDFDSDSSSSDSS_FAILURE = "DELETE_RECORDDFDSDSSSSDSS_FAILURE";