export const CREATE_CARLISTLLL = "CREATE_CARLISTLLL";
export const CREATE_CARLISTLLL_SUCCESS = "CREATE_CARLISTLLL_SUCCESS";
export const CREATE_CARLISTLLL_FAILURE = "CREATE_CARLISTLLLLOGIN_FAILURE";

export const GET_CARLISTLLL = "GET_CARLISTLLL";
export const GET_CARLISTLLL_SUCCESS = "GET_CARLISTLLL_SUCCESS";
export const GET_CARLISTLLL_FAILURE = "GET_CARLISTLLL_FAILURE";

export const UPDATE_CARLISTLLL = "UPDATE_CARLISTLLL";
export const UPDATE_CARLISTLLL_SUCCESS = "UPDATE_CARLISTLLL_SUCCESS";
export const UPDATE_CARLISTLLL_FAILURE = "UPDATE_CARLISTLLL_FAILURE";


export const DELETE_CARLISTLLL = "DELETE_CARLISTLLL";
export const DELETE_CARLISTLLL_SUCCESS = "DELETE_CARLISTLLL_SUCCESS";
export const DELETE_CARLISTLLL_FAILURE = "DELETE_CARLISTLLL_FAILURE";