export const CREATE_SSSS = "CREATE_SSSS";
export const CREATE_SSSS_SUCCESS = "CREATE_SSSS_SUCCESS";
export const CREATE_SSSS_FAILURE = "CREATE_SSSSLOGIN_FAILURE";

export const GET_SSSS = "GET_SSSS";
export const GET_SSSS_SUCCESS = "GET_SSSS_SUCCESS";
export const GET_SSSS_FAILURE = "GET_SSSS_FAILURE";

export const UPDATE_SSSS = "UPDATE_SSSS";
export const UPDATE_SSSS_SUCCESS = "UPDATE_SSSS_SUCCESS";
export const UPDATE_SSSS_FAILURE = "UPDATE_SSSS_FAILURE";


export const DELETE_SSSS = "DELETE_SSSS";
export const DELETE_SSSS_SUCCESS = "DELETE_SSSS_SUCCESS";
export const DELETE_SSSS_FAILURE = "DELETE_SSSS_FAILURE";