export const CREATE_RECORDSDDFDSDSSSSDSS = "CREATE_RECORDSDDFDSDSSSSDSS";
export const CREATE_RECORDSDDFDSDSSSSDSS_SUCCESS = "CREATE_RECORDSDDFDSDSSSSDSS_SUCCESS";
export const CREATE_RECORDSDDFDSDSSSSDSS_FAILURE = "CREATE_RECORDSDDFDSDSSSSDSSLOGIN_FAILURE";

export const GET_RECORDSDDFDSDSSSSDSS = "GET_RECORDSDDFDSDSSSSDSS";
export const GET_RECORDSDDFDSDSSSSDSS_SUCCESS = "GET_RECORDSDDFDSDSSSSDSS_SUCCESS";
export const GET_RECORDSDDFDSDSSSSDSS_FAILURE = "GET_RECORDSDDFDSDSSSSDSS_FAILURE";

export const UPDATE_RECORDSDDFDSDSSSSDSS = "UPDATE_RECORDSDDFDSDSSSSDSS";
export const UPDATE_RECORDSDDFDSDSSSSDSS_SUCCESS = "UPDATE_RECORDSDDFDSDSSSSDSS_SUCCESS";
export const UPDATE_RECORDSDDFDSDSSSSDSS_FAILURE = "UPDATE_RECORDSDDFDSDSSSSDSS_FAILURE";


export const DELETE_RECORDSDDFDSDSSSSDSS = "DELETE_RECORDSDDFDSDSSSSDSS";
export const DELETE_RECORDSDDFDSDSSSSDSS_SUCCESS = "DELETE_RECORDSDDFDSDSSSSDSS_SUCCESS";
export const DELETE_RECORDSDDFDSDSSSSDSS_FAILURE = "DELETE_RECORDSDDFDSDSSSSDSS_FAILURE";