export const CREATE_RECORDSSSS = "CREATE_RECORDSSSS";
export const CREATE_RECORDSSSS_SUCCESS = "CREATE_RECORDSSSS_SUCCESS";
export const CREATE_RECORDSSSS_FAILURE = "CREATE_RECORDSSSSLOGIN_FAILURE";

export const GET_RECORDSSSS = "GET_RECORDSSSS";
export const GET_RECORDSSSS_SUCCESS = "GET_RECORDSSSS_SUCCESS";
export const GET_RECORDSSSS_FAILURE = "GET_RECORDSSSS_FAILURE";

export const UPDATE_RECORDSSSS = "UPDATE_RECORDSSSS";
export const UPDATE_RECORDSSSS_SUCCESS = "UPDATE_RECORDSSSS_SUCCESS";
export const UPDATE_RECORDSSSS_FAILURE = "UPDATE_RECORDSSSS_FAILURE";


export const DELETE_RECORDSSSS = "DELETE_RECORDSSSS";
export const DELETE_RECORDSSSS_SUCCESS = "DELETE_RECORDSSSS_SUCCESS";
export const DELETE_RECORDSSSS_FAILURE = "DELETE_RECORDSSSS_FAILURE";